Fixing first line number and highlight
krzyzanowskim/STTextView pull request #65
Opened 2024-08-22 01:44 UTC by HassanTaleb90

2024-08-22 16:49 UTC, krzyzanowskim requested changes
thank you! it looks good overall. I think we should handle metric in a different way (and consistent with other places)

2024-08-22 16:49 UTC, krzyzanowskim commented on Sources/STTextViewAppKit/STTextView+Gutter.swift
> +        if viewportRange.isEmpty {
```suggestion
        if textLayoutManager.documentRange.isEmpty {
```

2024-08-22 16:49 UTC, krzyzanowskim commented on Sources/STTextViewAppKit/STTextView+Gutter.swift
> +            ]
```suggestion
            var effectiveLineTextAttributes = lineTextAttributes
```
`lineTextAttributes` is already defined above.

2024-08-22 16:49 UTC, krzyzanowskim commented on Sources/STTextViewAppKit/STTextView+Gutter.swift
> +                lineTextAttributes.merge(selectedLineTextAttributes, uniquingKeysWith: { _, new in new })
```suggestion
                effectiveLineTextAttributes.merge(selectedLineTextAttributes, uniquingKeysWith: { _, new in new })
```

2024-08-22 16:49 UTC, krzyzanowskim commented on Sources/STTextViewAppKit/STTextView+Gutter.swift
> +            let characterHeight = NSAttributedString(string: "\(lineNumber)", attributes: lineTextAttributes)
```suggestion
            let characterHeight = NSAttributedString(string: "\(lineNumber)", attributes: effectiveLineTextAttributes)
```

2024-08-22 16:49 UTC, krzyzanowskim commented on Sources/STTextViewAppKit/STTextView+Gutter.swift
> +
check out `updateSelectedLineHighlight()` how to get the same metric here

2024-08-22 17:02 UTC, HassanTaleb90 commented
In Xcode, I noticed that there is always a line break at the end of the file. So, I'm not sure if it would be better to follow the same approach. What do you think?

<img width="101" alt="Screenshot 2024-08-22 at 7 47 55 PM" src="https://github.com/user-attachments/assets/60a2b3b9-d558-42e7-b769-12fcf72a5fa1">

<img width="270" alt="Screenshot 2024-08-22 at 7 59 18 PM" src="https://github.com/user-attachments/assets/1a80a03a-9649-4dcf-afa1-bc20e2bd2c97">

2024-08-22 17:07 UTC, HassanTaleb90 reviewed
👍

2024-08-22 17:11 UTC, krzyzanowskim commented
> In Xcode, I noticed that there is always a line break at the end of the file

this last line is an `extraLineFragment` in our nomenclature. When it comes to the whitespace, better keep it in sync with the characters. if there's none, we should not add.

2024-08-22 17:40 UTC, HassanTaleb90 commented on Sources/STTextViewAppKit/STTextView+Gutter.swift
> +
Maybe like this, but in our case the viewportRange is empty
` var characterHeight: CGFloat = 0
            textLayoutManager.enumerateTextLayoutFragments(in: viewportRange) { layoutFragment in
                for lineFragment in layoutFragment.textLineFragments {
                    let lineFragmentHeight = lineFragment.typographicBounds.height
                    characterHeight = lineFragmentHeight
                    return false
                }
                return true
            }
         `

2024-08-23 15:42 UTC, krzyzanowskim commented
done in 141b60b313a4e58668971bbecb3165ca27ec200f

2024-08-23 15:42 UTC, closed without merging